version: "3"
services:
  db:
    image: mysql:8.0
    user: "1000"
    command: --max-allowed-packet=512M --innodb_use_native_aio=0
    volumes:
      - ./mysql-data-dir:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: gigco-supercharge
      MYSQL_DATABASE: gigco
      MYSQL_USER: gigco
      MYSQL_PASSWORD: ts0pSQBsw13Sq
    ports:
      - "3308:3306"
    expose:
      - "3306"

  web:
    build: ./virtualization/php/
    volumes:
      - .:/var/www/html/gigco/app
    links:
      - "db"

  nginx:
    build: ./virtualization/nginx/
    volumes:
      - ./virtualization/nginx/config:/etc/nginx/conf.d
      - .:/var/www/html/gigco/app
    ports:
      - 8090:80

    depends_on:
      - web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - "8093:80"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=gigco-supercharge
      - PHP_UPLOAD_MAX_FILESIZE=100MB

  maildev:
    image: djfarrelly/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
        - "1080:80"
        - "1025:25"
